# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'movie.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("\n"
"  background-color:#7c7275; /* Приятный коричневый оттенок (светло-коричневый) */\n"
"  background-image: none; /* Убираем изображение фона */\n"
"  color: #000000; /* Белый цвет текста */\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 600, 400))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setStyleSheet("QPushButton {\n"
"    background-color: white;            /* Белый фон */\n"
"    border: 3px solid black;            /* Черная граница */\n"
"    border-radius: 50px;                /* Округляем углы для овальной формы */\n"
"    width: 200px;                       /* Ширина кнопки */\n"
"    height: 100px;                      /* Высота кнопки */\n"
"    font-size: 16px;                    /* Размер шрифта */\n"
"    color: black;                       /* Цвет текста */\n"
"    text-align: center;                 /* Выравнивание текста по центру */\n"
"    line-height: 100px;                 /* Вертикальное выравнивание текста по центру */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: lightgray;        /* Цвет фона при нажатии */\n"
"    border-color: gray;                 /* Цвет границы при нажатии */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f0f0f0;          /* Цвет фона при наведении */\n"
"    border-color: #888;                 /* Цвет границы при наведении */\n"
"}\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(10, 20, 541, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.listWidget = QtWidgets.QListWidget(self.tab)
        self.listWidget.setGeometry(QtCore.QRect(10, 50, 581, 291))
        self.listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listWidget.setAutoScrollMargin(16)
        self.listWidget.setIconSize(QtCore.QSize(60, 60))
        self.listWidget.setObjectName("listWidget")
        font = QtGui.QFont()
        font.setPointSize(20)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.qrc.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(220, 30, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("font-size: 24px")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(20, 130, 121, 51))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("background: pink; color: green; font-size: 24px")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 130, 121, 51))
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet("background: pink; color: green; font-size: 24px")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(300, 130, 121, 51))
        self.pushButton_3.setAutoFillBackground(False)
        self.pushButton_3.setStyleSheet("background: pink; color: green; font-size: 24px")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(450, 130, 121, 51))
        self.pushButton_4.setAutoFillBackground(False)
        self.pushButton_4.setStyleSheet("background: pink; color: green; font-size: 24px")
        self.pushButton_4.setObjectName("pushButton_4")
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(350, 260, 191, 51))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("logo.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.a1 = QtWidgets.QPushButton(self.tab_3)
        self.a1.setGeometry(QtCore.QRect(20, 90, 41, 31))
        self.a1.setStyleSheet("QPushButton {\n"
"    background-color: white;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkred;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: blue; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.a1.setText("")
        self.a1.setObjectName("a1")
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(240, 20, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("font-size:36px")
        self.label_15.setObjectName("label_15")
        self.a5 = QtWidgets.QPushButton(self.tab_3)
        self.a5.setGeometry(QtCore.QRect(220, 90, 41, 31))
        self.a5.setStyleSheet("QPushButton {\n"
"    background-color: white;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkred;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: blue; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.a5.setText("")
        self.a5.setObjectName("a5")
        self.a4 = QtWidgets.QPushButton(self.tab_3)
        self.a4.setGeometry(QtCore.QRect(170, 90, 41, 31))
        self.a4.setStyleSheet("QPushButton {\n"
"    background-color: white;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkred;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: blue; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.a4.setText("")
        self.a4.setObjectName("a4")
        self.a3 = QtWidgets.QPushButton(self.tab_3)
        self.a3.setGeometry(QtCore.QRect(120, 90, 41, 31))
        self.a3.setStyleSheet("QPushButton {\n"
"    background-color: white;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkred;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: blue; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.a3.setText("")
        self.a3.setObjectName("a3")
        self.a2 = QtWidgets.QPushButton(self.tab_3)
        self.a2.setGeometry(QtCore.QRect(70, 90, 41, 31))
        self.a2.setStyleSheet("QPushButton {\n"
"    background-color: white;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkred;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: blue; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.a2.setText("")
        self.a2.setObjectName("a2")
        self.a6 = QtWidgets.QPushButton(self.tab_3)
        self.a6.setGeometry(QtCore.QRect(270, 90, 41, 31))
        self.a6.setStyleSheet("QPushButton {\n"
"    background-color: white;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkred;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: blue; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.a6.setText("")
        self.a6.setObjectName("a6")
        self.a7 = QtWidgets.QPushButton(self.tab_3)
        self.a7.setGeometry(QtCore.QRect(320, 90, 41, 31))
        self.a7.setStyleSheet("QPushButton {\n"
"    background-color: white;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkred;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: blue; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.a7.setText("")
        self.a7.setObjectName("a7")
        self.a8 = QtWidgets.QPushButton(self.tab_3)
        self.a8.setGeometry(QtCore.QRect(370, 90, 41, 31))
        self.a8.setStyleSheet("QPushButton {\n"
"    background-color: white;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkred;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: blue; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.a8.setText("")
        self.a8.setObjectName("a8")
        self.a9 = QtWidgets.QPushButton(self.tab_3)
        self.a9.setGeometry(QtCore.QRect(420, 90, 41, 31))
        self.a9.setStyleSheet("QPushButton {\n"
"    background-color: white;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkred;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: blue; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.a9.setText("")
        self.a9.setObjectName("a9")
        self.a10 = QtWidgets.QPushButton(self.tab_3)
        self.a10.setGeometry(QtCore.QRect(470, 90, 41, 31))
        self.a10.setStyleSheet("QPushButton {\n"
"    background-color: white;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkred;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: blue; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.a10.setText("")
        self.a10.setObjectName("a10")
        self.a11 = QtWidgets.QPushButton(self.tab_3)
        self.a11.setGeometry(QtCore.QRect(520, 90, 41, 31))
        self.a11.setStyleSheet("QPushButton {\n"
"    background-color: white;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkred;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: blue; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.a11.setText("")
        self.a11.setObjectName("a11")
        self.b1 = QtWidgets.QPushButton(self.tab_3)
        self.b1.setGeometry(QtCore.QRect(40, 140, 41, 31))
        self.b1.setStyleSheet("QPushButton {\n"
"    background-color: white;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkred;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: blue; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.b1.setText("")
        self.b1.setObjectName("b1")
        self.b3 = QtWidgets.QPushButton(self.tab_3)
        self.b3.setGeometry(QtCore.QRect(140, 140, 41, 31))
        self.b3.setStyleSheet("QPushButton {\n"
"    background-color: white;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkred;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: blue; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.b3.setText("")
        self.b3.setObjectName("b3")
        self.b2 = QtWidgets.QPushButton(self.tab_3)
        self.b2.setGeometry(QtCore.QRect(90, 140, 41, 31))
        self.b2.setStyleSheet("QPushButton {\n"
"    background-color: white;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkred;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: blue; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.b2.setText("")
        self.b2.setObjectName("b2")
        self.b4 = QtWidgets.QPushButton(self.tab_3)
        self.b4.setGeometry(QtCore.QRect(190, 140, 41, 31))
        self.b4.setStyleSheet("QPushButton {\n"
"    background-color: white;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkred;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: blue; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.b4.setText("")
        self.b4.setObjectName("b4")
        self.b5 = QtWidgets.QPushButton(self.tab_3)
        self.b5.setGeometry(QtCore.QRect(240, 140, 41, 31))
        self.b5.setStyleSheet("QPushButton {\n"
"    background-color: white;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkred;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: blue; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.b5.setText("")
        self.b5.setObjectName("b5")
        self.b8 = QtWidgets.QPushButton(self.tab_3)
        self.b8.setGeometry(QtCore.QRect(390, 140, 41, 31))
        self.b8.setStyleSheet("QPushButton {\n"
"    background-color: white;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkred;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: blue; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.b8.setText("")
        self.b8.setObjectName("b8")
        self.b9 = QtWidgets.QPushButton(self.tab_3)
        self.b9.setGeometry(QtCore.QRect(440, 140, 41, 31))
        self.b9.setStyleSheet("QPushButton {\n"
"    background-color: white;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkred;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: blue; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.b9.setText("")
        self.b9.setObjectName("b9")
        self.b6 = QtWidgets.QPushButton(self.tab_3)
        self.b6.setGeometry(QtCore.QRect(290, 140, 41, 31))
        self.b6.setStyleSheet("QPushButton {\n"
"    background-color: white;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkred;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: blue; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.b6.setText("")
        self.b6.setObjectName("b6")
        self.b7 = QtWidgets.QPushButton(self.tab_3)
        self.b7.setGeometry(QtCore.QRect(340, 140, 41, 31))
        self.b7.setStyleSheet("QPushButton {\n"
"    background-color: white;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkred;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: blue; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.b7.setText("")
        self.b7.setObjectName("b7")
        self.c3 = QtWidgets.QPushButton(self.tab_3)
        self.c3.setGeometry(QtCore.QRect(170, 190, 41, 31))
        self.c3.setStyleSheet("QPushButton {\n"
"    background-color: white;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkred;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: blue; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.c3.setText("")
        self.c3.setObjectName("c3")
        self.c4 = QtWidgets.QPushButton(self.tab_3)
        self.c4.setGeometry(QtCore.QRect(220, 190, 41, 31))
        self.c4.setStyleSheet("QPushButton {\n"
"    background-color: white;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkred;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: blue; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.c4.setText("")
        self.c4.setObjectName("c4")
        self.c1 = QtWidgets.QPushButton(self.tab_3)
        self.c1.setGeometry(QtCore.QRect(70, 190, 41, 31))
        self.c1.setStyleSheet("QPushButton {\n"
"    background-color: white;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkred;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: blue; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.c1.setText("")
        self.c1.setObjectName("c1")
        self.c2 = QtWidgets.QPushButton(self.tab_3)
        self.c2.setGeometry(QtCore.QRect(120, 190, 41, 31))
        self.c2.setStyleSheet("QPushButton {\n"
"    background-color: white;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkred;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: blue; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.c2.setText("")
        self.c2.setObjectName("c2")
        self.c7 = QtWidgets.QPushButton(self.tab_3)
        self.c7.setGeometry(QtCore.QRect(370, 190, 41, 31))
        self.c7.setStyleSheet("QPushButton {\n"
"    background-color: white;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkred;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: blue; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.c7.setText("")
        self.c7.setObjectName("c7")
        self.c8 = QtWidgets.QPushButton(self.tab_3)
        self.c8.setGeometry(QtCore.QRect(420, 190, 41, 31))
        self.c8.setStyleSheet("QPushButton {\n"
"    background-color: white;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkred;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: blue; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.c8.setText("")
        self.c8.setObjectName("c8")
        self.c5 = QtWidgets.QPushButton(self.tab_3)
        self.c5.setGeometry(QtCore.QRect(270, 190, 41, 31))
        self.c5.setStyleSheet("QPushButton {\n"
"    background-color: white;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkred;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: blue; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.c5.setText("")
        self.c5.setObjectName("c5")
        self.c6 = QtWidgets.QPushButton(self.tab_3)
        self.c6.setGeometry(QtCore.QRect(320, 190, 41, 31))
        self.c6.setStyleSheet("QPushButton {\n"
"    background-color: white;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkred;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: blue; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.c6.setText("")
        self.c6.setObjectName("c6")
        self.b10 = QtWidgets.QPushButton(self.tab_3)
        self.b10.setGeometry(QtCore.QRect(490, 140, 41, 31))
        self.b10.setStyleSheet("QPushButton {\n"
"    background-color: white;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkred;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: blue; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.b10.setText("")
        self.b10.setObjectName("b10")
        self.c9 = QtWidgets.QPushButton(self.tab_3)
        self.c9.setGeometry(QtCore.QRect(470, 190, 41, 31))
        self.c9.setStyleSheet("QPushButton {\n"
"    background-color: white;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkred;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: blue; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.c9.setText("")
        self.c9.setObjectName("c9")
        self.d2 = QtWidgets.QPushButton(self.tab_3)
        self.d2.setGeometry(QtCore.QRect(150, 240, 41, 31))
        self.d2.setStyleSheet("QPushButton {\n"
"    background-color: white;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkred;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: blue; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.d2.setText("")
        self.d2.setObjectName("d2")
        self.d3 = QtWidgets.QPushButton(self.tab_3)
        self.d3.setGeometry(QtCore.QRect(200, 240, 41, 31))
        self.d3.setStyleSheet("QPushButton {\n"
"    background-color: white;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkred;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: blue; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.d3.setText("")
        self.d3.setObjectName("d3")
        self.d1 = QtWidgets.QPushButton(self.tab_3)
        self.d1.setGeometry(QtCore.QRect(100, 240, 41, 31))
        self.d1.setStyleSheet("QPushButton {\n"
"    background-color: white;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkred;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: blue; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.d1.setText("")
        self.d1.setObjectName("d1")
        self.d4 = QtWidgets.QPushButton(self.tab_3)
        self.d4.setGeometry(QtCore.QRect(250, 240, 41, 31))
        self.d4.setStyleSheet("QPushButton {\n"
"    background-color: white;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkred;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: blue; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.d4.setText("")
        self.d4.setObjectName("d4")
        self.d7 = QtWidgets.QPushButton(self.tab_3)
        self.d7.setGeometry(QtCore.QRect(400, 240, 41, 31))
        self.d7.setStyleSheet("QPushButton {\n"
"    background-color: white;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkred;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: blue; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.d7.setText("")
        self.d7.setObjectName("d7")
        self.d8 = QtWidgets.QPushButton(self.tab_3)
        self.d8.setGeometry(QtCore.QRect(450, 240, 41, 31))
        self.d8.setStyleSheet("QPushButton {\n"
"    background-color: white;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkred;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: blue; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.d8.setText("")
        self.d8.setObjectName("d8")
        self.d5 = QtWidgets.QPushButton(self.tab_3)
        self.d5.setGeometry(QtCore.QRect(300, 240, 41, 31))
        self.d5.setStyleSheet("QPushButton {\n"
"    background-color: white;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkred;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: blue; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.d5.setText("")
        self.d5.setObjectName("d5")
        self.d6 = QtWidgets.QPushButton(self.tab_3)
        self.d6.setGeometry(QtCore.QRect(350, 240, 41, 31))
        self.d6.setStyleSheet("QPushButton {\n"
"    background-color: white;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkred;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: blue; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.d6.setText("")
        self.d6.setObjectName("d6")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(380, 290, 191, 51))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("logo.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_7.setGeometry(QtCore.QRect(230, 300, 101, 41))
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    background-color: green;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkgreen;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: forestgreen; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_12 = QtWidgets.QLabel(self.tab_4)
        self.label_12.setGeometry(QtCore.QRect(90, 180, 111, 31))
        self.label_12.setAutoFillBackground(False)
        self.label_12.setStyleSheet("font-size:20px; color: pink")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_4)
        self.label_13.setGeometry(QtCore.QRect(90, 130, 111, 31))
        self.label_13.setAutoFillBackground(False)
        self.label_13.setStyleSheet("font-size:20px; color: pink")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_4)
        self.label_14.setGeometry(QtCore.QRect(90, 80, 111, 31))
        self.label_14.setAutoFillBackground(False)
        self.label_14.setStyleSheet("font-size:20px; color: pink")
        self.label_14.setObjectName("label_14")
        self.label_16 = QtWidgets.QLabel(self.tab_4)
        self.label_16.setGeometry(QtCore.QRect(180, 20, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("font-size:24px")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab_4)
        self.label_17.setGeometry(QtCore.QRect(90, 230, 111, 31))
        self.label_17.setAutoFillBackground(False)
        self.label_17.setStyleSheet("font-size:20px; color: pink")
        self.label_17.setObjectName("label_17")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_3.setGeometry(QtCore.QRect(240, 80, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background: white; color: black; font-size: 15px")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setFrame(False)
        self.lineEdit_3.setDragEnabled(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_4.setGeometry(QtCore.QRect(240, 130, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("background: white; color: black; font-size: 15px")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setFrame(False)
        self.lineEdit_4.setDragEnabled(False)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_5.setGeometry(QtCore.QRect(240, 180, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("background: white; color: black; font-size: 15px")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setFrame(False)
        self.lineEdit_5.setDragEnabled(False)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_6.setGeometry(QtCore.QRect(240, 230, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet("background: white; color: black; font-size: 15px")
        self.lineEdit_6.setText("")
        self.lineEdit_6.setFrame(False)
        self.lineEdit_6.setDragEnabled(False)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(380, 290, 191, 51))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("logo.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_8.setGeometry(QtCore.QRect(240, 300, 81, 31))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_9.setGeometry(QtCore.QRect(160, 300, 81, 31))
        self.pushButton_9.setObjectName("pushButton_9")
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "  search...🔍"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Movies"))
        self.label.setText(_translate("MainWindow", "\"Кино\""))
        self.pushButton.setText(_translate("MainWindow", "10:30"))
        self.pushButton_2.setText(_translate("MainWindow", "12:30"))
        self.pushButton_3.setText(_translate("MainWindow", "14:30"))
        self.pushButton_4.setText(_translate("MainWindow", "16:30"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Schedule"))
        self.label_15.setText(_translate("MainWindow", "seats"))
        self.pushButton_7.setText(_translate("MainWindow", "next"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Seats"))
        self.label_12.setText(_translate("MainWindow", "price:"))
        self.label_13.setText(_translate("MainWindow", "seats:"))
        self.label_14.setText(_translate("MainWindow", "movie:"))
        self.label_16.setText(_translate("MainWindow", "your ticket✔"))
        self.label_17.setText(_translate("MainWindow", "total:"))
        self.pushButton_8.setText(_translate("MainWindow", "buy"))
        self.pushButton_9.setText(_translate("MainWindow", "cancel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Buy"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
