# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'my1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_register(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Cinema: Login")
        MainWindow.resize(609, 432)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(124, 114, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(124, 114, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(124, 114, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(124, 114, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(124, 114, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(124, 114, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(124, 114, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(124, 114, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(124, 114, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        MainWindow.setPalette(palette)
        MainWindow.setStyleSheet("\n"
"  background-color:#7c7275; /* Приятный коричневый оттенок (светло-коричневый) */\n"
"  background-image: none; /* Убираем изображение фона */\n"
"  color: #fff; /* Белый цвет текста */\n"
"")
        MainWindow.setAnimated(True)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 631, 421))
        self.tabWidget.setStyleSheet("QTabWidget {\n"
"    border: none; /* Убираем рамку у всего QTabWidget */\n"
"    padding: 0;   /* Убираем отступы */\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    border: none; /* Убираем рамку у вкладок */\n"
"    padding: 10px; /* Настройте отступы для вкладок */\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    border: none; /* Убираем рамку у выбранной вкладки */\n"
"    background-color: transparent; /* Сделать фон вкладки прозрачным */\n"
"}\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(80, 20, 451, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("font-size: 24px")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(300, 270, 281, 71))
        self.label_2.setText("")
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(180, 110, 211, 41))
        self.pushButton.setStyleSheet("background: white;\n"
"font-size: 18px;\n"
"color: black")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 190, 211, 41))
        self.pushButton_2.setStyleSheet("background: white;\n"
"font-size: 18px;\n"
"color: black")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(350, 260, 211, 71))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("logo.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(90, 10, 501, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font-size:24px")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(50, 110, 111, 31))
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet("font-size:20px; color: pink")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(50, 180, 111, 31))
        self.label_5.setAutoFillBackground(False)
        self.label_5.setStyleSheet("font-size:20px; color: pink")
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit.setGeometry(QtCore.QRect(210, 110, 251, 31))
        self.lineEdit.setPlaceholderText("Enter your name or nickname")
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background: white; color: black; font-size: 15px")
        self.lineEdit.setFrame(False)
        self.lineEdit.setDragEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(210, 180, 251, 31))
        self.lineEdit_3.setPlaceholderText("Enter your password")
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background: white; color: black; font-size: 15px")
        self.lineEdit_3.setFrame(False)
        self.lineEdit_3.setDragEnabled(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_5.setGeometry(QtCore.QRect(200, 280, 151, 41))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: green;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkgreen;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: forestgreen; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(400, 300, 201, 51))
        self.label_11.setText("")
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(370, 280, 191, 51))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("logo.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_12 = QtWidgets.QLabel(self.tab_5)
        self.label_12.setGeometry(QtCore.QRect(100, 90, 111, 31))
        self.label_12.setAutoFillBackground(False)
        self.label_12.setStyleSheet("font-size:20px; color: pink")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_5)
        self.label_13.setGeometry(QtCore.QRect(100, 150, 111, 31))
        self.label_13.setAutoFillBackground(False)
        self.label_13.setStyleSheet("font-size:20px; color: pink")
        self.label_13.setObjectName("label_13")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_4.setGeometry(QtCore.QRect(250, 90, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("background: white; color: black; font-size: 15px")
        self.lineEdit_4.setPlaceholderText("Enter your name or nickname")
        self.lineEdit_4.setFrame(False)
        self.lineEdit_4.setDragEnabled(False)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_5.setGeometry(QtCore.QRect(250, 150, 251, 31))
        self.lineEdit_5.setPlaceholderText("Enter your password")
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("background: white; color: black; font-size: 15px")
        self.lineEdit_5.setFrame(False)
        self.lineEdit_5.setDragEnabled(False)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_6.setGeometry(QtCore.QRect(190, 300, 151, 41))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: green;       /* Зеленый цвет фона */\n"
"    border-radius: 15px;           /* Овальная форма (скругление углов) */\n"
"    color: white;                  /* Белый цвет текста */\n"
"    padding: 10px 20px;            /* Отступы внутри кнопки */\n"
"    border: none;                  /* Убираем рамку */\n"
"    font-size: 16px;               /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: darkgreen;  /* Цвет фона при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: forestgreen; /* Цвет фона при нажатии */\n"
"}\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.radioButton = QtWidgets.QRadioButton(self.tab_5)
        self.radioButton.setGeometry(QtCore.QRect(90, 220, 411, 31))
        self.radioButton.setStyleSheet("QRadioButton {\n"
"    font-size: 20px;                /* Размер текста */\n"
"    color: darkblue;                /* Темно-синий цвет текста */\n"
"    padding-left: 10px;             /* Отступ от круга до текста */\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 20px;                    /* Уменьшаем размер круга */\n"
"    height: 20px;                   /* Уменьшаем размер круга */\n"
"    border-radius: 10px;            /* Округляем края, чтобы сохранить круглый вид */\n"
"    border: 2px solid darkblue;     /* Граница круга */\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: darkblue;     /* Цвет круга, когда радиокнопка выбрана */\n"
"    border: 2px solid darkblue;     /* Граница круга при выбранном состоянии */\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color: white;        /* Цвет круга, когда радиокнопка не выбрана */\n"
"    border: 2px solid darkblue;     /* Граница круга при невыбранном состоянии */\n"
"}\n"
"")
        self.radioButton.setObjectName("radioButton")
        self.radioButton.setChecked(False)
        self.label_15 = QtWidgets.QLabel(self.tab_5)
        self.label_15.setGeometry(QtCore.QRect(40, 10, 531, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("font-size:24px")
        self.label_15.setObjectName("label_15")
        self.label_8 = QtWidgets.QLabel(self.tab_5)
        self.label_8.setGeometry(QtCore.QRect(370, 290, 191, 51))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("logo.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.tabWidget.addTab(self.tab_5, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 609, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "\"Your ticket to the world of cinema!\""))
        self.pushButton.setText(_translate("MainWindow", "login"))
        self.pushButton_2.setText(_translate("MainWindow", "register"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Home"))
        self.label_3.setText(_translate("MainWindow", "Welcome back! Log in to your account."))
        self.label_4.setText(_translate("MainWindow", "name:"))
        self.label_5.setText(_translate("MainWindow", "password:"))
        # self.lineEdit.setText(_translate("MainWindow", "enter your name or nickname"))
        # self.lineEdit_3.setText(_translate("MainWindow", "enter your password"))
        self.pushButton_5.setText(_translate("MainWindow", "login"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Login"))
        self.label_12.setText(_translate("MainWindow", "name:"))
        self.label_13.setText(_translate("MainWindow", "password:"))
        # self.lineEdit_4.setText(_translate("MainWindow", "enter your name or nickname"))
        # self.lineEdit_5.setText(_translate("MainWindow", "enter your password"))
        self.pushButton_6.setText(_translate("MainWindow", "register"))
        self.radioButton.setText(_translate("MainWindow", "I\'m not a robot!!! Trust me my friend😊"))
        self.label_15.setText(_translate("MainWindow", "Welcome! Register and create your profile."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Register"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_login_register()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
